config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'psgc/fetch_provinces', to: 'psgc#fetch_provinces'
    get 'psgc/fetch_cities_municipalities/:province_code', to: 'psgc#fetch_cities_municipalities'
    get 'psgc/fetch_barangays/:city_or_municipality_code', to: 'psgc#fetch_barangays'
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    root to: "devise/sessions#new"
  end
  
  patch 'profile/update_profile_picture', to: 'profile#update_profile_picture', as: 'update_profile_picture'
  
  namespace :admin do
    resources :dashboard, only: [:index] do
      post :create_admin_account, on: :collection
    end
    
    resources :residents do
      collection do
        get 'pending', to: 'residents#pending'
      end
    end 
    
    resources :announcements
    resources :complaints, only: [:index, :edit, :update, :show]
    resources :posts
  end


  namespace :resident do
    resources :dashboard, only: [:index]
    resources :posts, only: [:index, :new, :create, :show] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
      collection do
        get 'my_posts', to: 'posts#my_posts'
      end
    end
    resources :announcements, only: [:index, :show]
    resources :complaints, only: [:index, :show, :new, :create]
    
  end
end


app/controllers/admin/residents_controller.rb
class Admin::ResidentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: %i[show edit update destroy]
  
    def index
      @users = User.where(
              role: :resident,
              status: 'approved',
              barangay: current_user.barangay,
              city_municipality: current_user.city_municipality,
              province: current_user.province
              )
      if params[:last_name_query].present?
        @users = @users.where("LOWER(last_name) LIKE ?", "%#{params[:last_name_query].downcase}%")
      end
    end

    def pending
      @pending_users = User.where(
        role: :resident,
        status: 'pending',
        barangay: current_user.barangay,
        city_municipality: current_user.city_municipality,
        province: current_user.province
        )

        render :pending
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(resident_params)
      if @user.save
        UserMailer.registration_confirmation(@user).deliver_now
        redirect_to admin_residents_path, notice: "Resident's account was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def show
    end
  
    def edit
    end
  
    def update
      if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end

      if @user.update(resident_params)
        if @user.saved_change_to_status?
          if @user.status == 'approved'
            UserMailer.approved_email(@user).deliver_later
          elsif @user.status == 'rejected'
            UserMailer.rejected_email(@user).deliver_later
          end
        end
        redirect_to admin_residents_path, notice: "Resident's account was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @user.destroy
      redirect_to admin_residents_path, notice: "Resident's account was successfully deleted."
    end
  
    private
  
    def set_user
      @user = User.find(params[:id])
    end
  
    def resident_params
      params.require(:user).permit(:id, :first_name, :last_name, :email, :password, :password_confirmation, :complete_address, :barangay, :province, :city_municipality, :role, :status, :contact_number)
    end
end

app/controllers/resident/announcements_controller.rb
class Resident::AnnouncementsController < ApplicationController
    def index
        @announcements = Announcement.joins(:user)
                                .where(users: { role: 'admin', 
                                               barangay: current_user.barangay, 
                                               city_municipality: current_user.city_municipality,
                                               province: current_user.province })
                                .order(created_at: :desc)
      end
    
      def show
        @announcement = Announcement.find(params[:id])
      end
end

app/controllers/resident/comments_controller.rb
class Resident::CommentsController < ApplicationController
    class Resident::CommentsController < ApplicationController
        def create
          @comment = current_user.comments.new(comment_params)
      
          if @comment.save
            flash[:notice] = "Comment added successfully."
          elsif !@comment.save
            flash[:alert] = @comment.errors.full_messages.to_sentence
          end
          redirect_back(fallback_location: root_path)
        end
      
        def destroy
          @comment = current_user.comments.find(params[:id])
          @comment.destroy
          flash[:notice] = "Comment deleted successfully."
          redirect_back(fallback_location: root_path)
        rescue ActiveRecord::RecordNotFound
          flash[:alert] = "Comment not found."
          redirect_back(fallback_location: root_path)
        end
      
        private
      
        def comment_params
          params
          .require(:comment)
          .permit(:content)
          .merge(post_id: params[:post_id])
        end
      end
      
      
end

app/controllers/resident/complaints_controller.rb
class Resident::ComplaintsController < ApplicationController
    class Resident::ComplaintsController < ApplicationController
        before_action :authenticate_user!
        
        def index
          @complaints = current_user.complaints
        end
      
        def show
          @complaint = Complaint.find(params[:id])
        end
      
        def new
          @complaint = Complaint.new
        end
      
        def create
          @complaint = current_user.complaints.build(complaint_params)
          if @complaint.save
            redirect_to resident_complaints_path, notice: 'Complaint was reported to barangay admin.'
          else
            render :new, status: :unprocessable_entity
          end
      
        end
      
        private
      
        def complaint_params
          params.require(:complaint).permit(:subject, :description, :status)
        end
      
      end
      
end

app/controllers/resident/dashboard_controller.rb
class Resident::DashboardController < ApplicationController
    class Resident::DashboardController < ApplicationController
        before_action :authenticate_user!
        before_action :set_post, only: [:edit, :update, :destroy]
      
        def index
          @posts = Post.all
          @post = Post.new
          @announcements = Announcement.joins(:user)
                                  .where(users: { role: 'admin', 
                                                 barangay: current_user.barangay, 
                                                 city_municipality: current_user.city_municipality,
                                                 province: current_user.province })
                                  .order(created_at: :desc)
                                  .limit(3)
    
        end
      
        def new
          @post = Post.new
        end
      
        def create
          @post = current_user.posts.build(post_params)
      
          if @post.save
            redirect_to resident_dashboard_path, notice: 'Post created successfully.'
          else
            render :new
          end
        end
      
        def edit
        end
      
        def update
          if @post.update(post_params)
            redirect_to resident_dashboard_path, notice: 'Post updated successfully.'
          else
            render :edit
          end
        end
      
        def destroy
          @post.destroy
          redirect_to resident_dashboard_path, notice: 'Post deleted successfully.'
        end
      
        private
      
        def set_post
          @post = current_user.posts.find(params[:id])
        end
      
        def post_params
          params.require(:post).permit(:title, :content)
        end
      end
      
end

app/controllers/resident/likes_controller.rb
class Resident::LikesController < ApplicationController
    class Resident::LikesController < ApplicationController
        def create
            @like = current_user.likes.new(like_params)
    
            if !@like.save
                flash[:notice] = @like.errors.full_messages.to_sentence
            end
    
            redirect_back(fallback_location: root_path)
        end
    
        def destroy
            @like = current_user.likes.find(params[:id])
            post = @like.post
            @like.destroy
            redirect_back(fallback_location: root_path)
        end
    
        private
    
        def like_params
            params.require(:like).permit(:post_id)
        end
    end
    
end

app/controllers/resident/posts_controller.rb
class Resident::PostsController < ApplicationController
    before_action :authenticate_user!

    def index
      current_user_location = {
        province: current_user.province,
        city_municipality: current_user.city_municipality,
        barangay: current_user.barangay
      }
  
      @posts = Post.joins(:user)
                       .where(users: { status: 'approved', province: current_user_location[:province], city_municipality: current_user_location[:city_municipality], barangay: current_user_location[:barangay] })
      @comments = Comment.all
  
      if params[:content_query].present?
        @posts = @posts.where("LOWER(content) LIKE ?", "%#{params[:content_query].downcase}%")
      end
    
    end
  
    def my_posts
      @user_posts = current_user.posts 
    end
  
    def new
      @post = Post.new
    end
  
    def create
      @post = current_user.posts.build(post_params)
  
      if @post.save
        redirect_to resident_posts_path notice: 'Post created successfully.'
      else
        render :new
      end
    end
  
    private
  
    def post_params
      params.require(:post).permit(:title, :content, :anonymous)
    end
end

app/helpers/admin/residents_helper.rb
module Admin::ResidentsHelper
end

app/helpers/resident/announcements_helper.rb
module Resident::AnnouncementsHelper
end

app/helpers/resident/comments_helper.rb
module Resident::CommentsHelper
end

app/helpers/resident/complaints_helper.rb
module Resident::ComplaintsHelper
end

app/helpers/resident/dashboard_helper.rb
module Resident::DashboardHelper
end

app/helpers/resident/likes_helper.rb
module Resident::LikesHelper
end

app/helpers/resident/posts_helper.rb
module Resident::PostsHelper
end

app/views/admin/residents/_edit_status.html.erb
<%= form_with(model: [:admin, user], url: admin_resident_path(user), method: :patch, local: true) do |form| %>
  <div class="status-button-container">
    <div class="edit-status-form">
      <%= form.button "Approve", type: :submit, class: "approve-button", name: 'user[status]', value: 'approved' %>
    </div>
    <div class="edit-status-form">
      <%= form.button "Reject", type: :submit, class: "reject-button", name: 'user[status]', value: 'rejected' %>
    </div>
  </div>
<% end %>

app/views/admin/residents/_form.html.erb
<%= form_with(model: [:admin, user], url: user.persisted? ? admin_resident_path(user) : admin_residents_path, local: true, class: "resident-form") do |form| %>
  
  <% if user.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
      <% user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
  <% end %>


  <div class="new-resident-field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "reg-input create-resident-field" %>
  </div>

  <div class="new-resident-field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "reg-input create-resident-field" %>
  </div>

  <div class="new-resident-field">
    <%= form.label :email %><br />
    <%= form.email_field :email, autofocus: true, autocomplete: "email", class: "reg-input create-resident-field" %>
  </div>

   <div class="new-resident-field">
    <%= form.label :contact_number %><br />
    <%= form.text_field :contact_number, autofocus: true, class: "reg-input create-resident-field", placeholder: "09*********" %>
  </div>

  <div class="new-resident-field">
    <%= form.label :complete_address %>
    <%= form.text_field :complete_address, class: "reg-input create-resident-field" %>
  </div>

  <div class="new-resident-field">
    <%= form.label :password %>
    <%= form.password_field :password, class: "reg-input create-resident-field" %>
  </div>

  <div class="new-resident-field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "reg-input create-resident-field" %>
  </div>

  <%= form.hidden_field :role, value: 'resident' %>
  <%= form.hidden_field :status, value: 'approved' %>
  <%= form.hidden_field :province, value: current_user.province %>
  <%= form.hidden_field :city_municipality, value: current_user.city_municipality %>
  <%= form.hidden_field :barangay, value: current_user.barangay %>
  <br>
  <div class="actions">
    <%= form.submit "Submit", class: "user-submit action-link" %>
  </div>
<% end %>

app/views/admin/residents/edit.html.erb
<div class = "wrapper-new-edit">
    <h1 class="page-title">Edit resident info</h1>
    <%= render 'form', user: @user %>
</div>

app/views/admin/residents/index.html.erb
<div class="residents-index-wrapper">
  <h1 class="page-title"> Registered Residents of BRGY.<%= current_user.barangay.upcase %></h1>

  <div class="residents-index-actions">
    <%= link_to 'Add Resident', new_admin_resident_path, class: "action-link" %>
    <%= link_to 'Pending Accounts', pending_admin_residents_path, class: "action-link" %>
  </div>

  <div class="search-line">
    <%= form_tag(admin_residents_path, method: :get, class: "search-form") do %>
      <%= text_field_tag :last_name_query, params[:last_name_query], placeholder: "Search by last name", class: "search-input" %>
      <%= submit_tag "Search", class:"search-submit" %>
    <% end %>
  </div>

  <div class="residents-index-container">
    <% @users.sort_by { |resident| [resident.last_name, resident.first_name] }.each do |user| %>
      <div class="indiv-resident">
        <p><strong style="color: #5C821A;">Name:</strong> <%= link_to "#{user.last_name}, #{user.first_name}", admin_resident_path(user), class: "name-link" %></p>
        <p><strong style="color: #5C821A;">Email:</strong> <%= user.email %></p>
        <p><strong style="color: #5C821A;">Contact Number:</strong> <%= user.contact_number %></p>
        <p><strong style="color: #5C821A;">Complete Address:</strong> <%= user.complete_address.titleize %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/residents/new.html.erb
<div class = "wrapper-new-edit">
    <h1 class="page-title">Add new Resident</h1>
    <%= render 'form', user: @user %>
</div>

app/views/admin/residents/pending.html.erb
<div class="residents-index-wrapper">
  <h1 class="page-title">Pending Residents of BRGY.<%= current_user.barangay.upcase %></h1>
  <p class="page-description">Please verify from current records if applicant truly resides in BRGY. <%= current_user.barangay.upcase %>. If not, reject account registration.</p>
  <div class="residents-index-actions">
    <%= link_to 'Back', admin_residents_path, class: "action-link" %>
  </div>

  <% if @pending_users.any? %>
    <div class="pending-index-container">
      <% @pending_users.order(created_at: :asc).each do |user| %>
        <div class="indiv-resident">
          <p><strong style="color: #5C821A;">Last Name:</strong> <%= user.last_name.titleize %></p>
          <p><strong style="color: #5C821A;">First Name:</strong> <%= user.first_name.titleize %></p>
          <p><strong style="color: #5C821A;">Email:</strong> <%= user.email %></p>
          <p><strong style="color: #5C821A;">Contact Number:</strong> <%= user.contact_number %></p>
          <p><strong style="color: #5C821A;">Complete Address:</strong> <%= user.complete_address.titleize %></p>
          <p><strong style="color: #5C821A;">Status:</strong> <%= user.status.titleize %></p>
          <p><strong style="color: #5C821A;">Regitration Date:</strong> <%= user.created_at.in_time_zone('Asia/Manila').strftime('%d %b %Y, %H:%M:%S') %></p>

          <%= render partial: 'edit_status', locals: { user: user } %>

        </div>
      <% end %>
    </div>
  <% else %>
    <p>No pending residents at the moment.</p>
  <% end %>
</div>

app/views/admin/residents/show.html.erb
<div class="show-resident-wrapper">
  <h1 class="page-title">Resident Details</h1>

  <div class="show-resident-details">

    <div class = "show-resident-profile-pic">
      <% if @user.image.attached? %>
        <%= image_tag(@user.image, style: "height:120px; width:120px", class: 'avatar') %>
      <% end %>
    </div>
   
    <p><strong style="color: #5C821A;">Last Name:</strong> <%= @user.last_name.titleize %></p>
    <p><strong style="color: #5C821A;">First Name:</strong> <%= @user.first_name.titleize %></p>
    <p><strong style="color: #5C821A;">User ID:</strong> <%= @user.id %></p>
    <p><strong style="color: #5C821A;">Email:</strong> <%= @user.email %></p>
    <p><strong style="color: #5C821A;">Contact Number:</strong> <%= @user.contact_number %></p>
    <p><strong style="color: #5C821A;">Complete Address:</strong> <%= @user.complete_address.titleize %></p>
    <p><strong style="color: #5C821A;">Status:</strong> <%= @user.status.titleize %></p>
    <p><strong style="color: #5C821A;">Regitration Date:</strong> <%= @user.created_at.in_time_zone('Asia/Manila').strftime('%d %b %Y, %H:%M:%S') %></p>

    <div class="show-resident-actions">
      <%= link_to 'Back', admin_residents_path, class: "action-link" %>
      <%= link_to 'Edit', edit_admin_resident_path(@user), class: "action-link" %>
      <%= button_to 'Destroy', admin_resident_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-button action-link"  %>
    </div>
  </div>
</div>