config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'psgc/fetch_provinces', to: 'psgc#fetch_provinces'
    get 'psgc/fetch_cities_municipalities/:province_code', to: 'psgc#fetch_cities_municipalities'
    get 'psgc/fetch_barangays/:city_or_municipality_code', to: 'psgc#fetch_barangays'
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    root to: "devise/sessions#new"
  end
  
  patch 'profile/update_profile_picture', to: 'profile#update_profile_picture', as: 'update_profile_picture'
  
  namespace :admin do
    resources :dashboard, only: [:index] do
      post :create_admin_account, on: :collection
    end
    
    resources :residents do
      collection do
        get 'pending', to: 'residents#pending'
      end
    end 
    
    resources :announcements
    resources :complaints, only: [:index, :edit, :update, :show]
    resources :posts
  end


  namespace :resident do
    resources :dashboard, only: [:index]
    resources :posts, only: [:index, :new, :create, :show] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
      collection do
        get 'my_posts', to: 'posts#my_posts'
      end
    end
    resources :announcements, only: [:index, :show]
    resources :complaints, only: [:index, :show, :new, :create]
    
  end
end


app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
    def index
        @announcement = Announcement.joins(:user)
        .where(users: { role: 'admin', 
                       barangay: current_user.barangay, 
                       city_municipality: current_user.city_municipality,
                       province: current_user.province })
        .last
    
        @complaints = Complaint.joins(:user).where(users: { 
        barangay: current_user.barangay,
        city_municipality: current_user.city_municipality,
        province: current_user.province
      }).where(status: 'pending').order(created_at: :desc).limit(3)
      end
    
      def create_admin_account
        admin = Admin.create!(
          email: "admin@example.com",
          password: "adminpassword",
          password_confirmation: "adminpassword"
        )
        if admin.persisted?
          flash[:notice] = "Admin account created successfully!"
          redirect_to admin_dashboard_path
        else
          flash[:alert] = "Failed to create admin account"
          redirect_to admin_dashboard_path
        end
      end
end

app/controllers/admin/residents_controller.rb
class Admin::ResidentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: %i[show edit update destroy]
  
    def index
      @users = User.where(
              role: :resident,
              status: 'approved',
              barangay: current_user.barangay,
              city_municipality: current_user.city_municipality,
              province: current_user.province
              )
      if params[:last_name_query].present?
        @users = @users.where("LOWER(last_name) LIKE ?", "%#{params[:last_name_query].downcase}%")
      end
    end

    def pending
      @pending_users = User.where(
        role: :resident,
        status: 'pending',
        barangay: current_user.barangay,
        city_municipality: current_user.city_municipality,
        province: current_user.province
        )

        render :pending
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(resident_params)
      if @user.save
        UserMailer.registration_confirmation(@user).deliver_now
        redirect_to admin_residents_path, notice: "Resident's account was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def show
    end
  
    def edit
    end
  
    def update
      if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end

      if @user.update(resident_params)
        if @user.saved_change_to_status?
          if @user.status == 'approved'
            UserMailer.approved_email(@user).deliver_later
          elsif @user.status == 'rejected'
            UserMailer.rejected_email(@user).deliver_later
          end
        end
        redirect_to admin_residents_path, notice: "Resident's account was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @user.destroy
      redirect_to admin_residents_path, notice: "Resident's account was successfully deleted."
    end
  
    private
  
    def set_user
      @user = User.find(params[:id])
    end
  
    def resident_params
      params.require(:user).permit(:id, :first_name, :last_name, :email, :password, :password_confirmation, :complete_address, :barangay, :province, :city_municipality, :role, :status, :contact_number)
    end
end

app/controllers/resident/announcements_controller.rb
class Resident::AnnouncementsController < ApplicationController
    def index
        @announcements = Announcement.joins(:user)
                                .where(users: { role: 'admin', 
                                               barangay: current_user.barangay, 
                                               city_municipality: current_user.city_municipality,
                                               province: current_user.province })
                                .order(created_at: :desc)
      end
    
      def show
        @announcement = Announcement.find(params[:id])
      end
end

app/controllers/resident/comments_controller.rb
class Resident::CommentsController < ApplicationController
    class Resident::CommentsController < ApplicationController
        def create
          @comment = current_user.comments.new(comment_params)
      
          if @comment.save
            flash[:notice] = "Comment added successfully."
          elsif !@comment.save
            flash[:alert] = @comment.errors.full_messages.to_sentence
          end
          redirect_back(fallback_location: root_path)
        end
      
        def destroy
          @comment = current_user.comments.find(params[:id])
          @comment.destroy
          flash[:notice] = "Comment deleted successfully."
          redirect_back(fallback_location: root_path)
        rescue ActiveRecord::RecordNotFound
          flash[:alert] = "Comment not found."
          redirect_back(fallback_location: root_path)
        end
      
        private
      
        def comment_params
          params
          .require(:comment)
          .permit(:content)
          .merge(post_id: params[:post_id])
        end
      end
      
      
end

app/controllers/resident/complaints_controller.rb
class Resident::ComplaintsController < ApplicationController
    class Resident::ComplaintsController < ApplicationController
        before_action :authenticate_user!
        
        def index
          @complaints = current_user.complaints
        end
      
        def show
          @complaint = Complaint.find(params[:id])
        end
      
        def new
          @complaint = Complaint.new
        end
      
        def create
          @complaint = current_user.complaints.build(complaint_params)
          if @complaint.save
            redirect_to resident_complaints_path, notice: 'Complaint was reported to barangay admin.'
          else
            render :new, status: :unprocessable_entity
          end
      
        end
      
        private
      
        def complaint_params
          params.require(:complaint).permit(:subject, :description, :status)
        end
      
      end
      
end

app/controllers/resident/dashboard_controller.rb
class Resident::DashboardController < ApplicationController
    class Resident::DashboardController < ApplicationController
        before_action :authenticate_user!
        before_action :set_post, only: [:edit, :update, :destroy]
      
        def index
          @posts = Post.all
          @post = Post.new
          @announcements = Announcement.joins(:user)
                                  .where(users: { role: 'admin', 
                                                 barangay: current_user.barangay, 
                                                 city_municipality: current_user.city_municipality,
                                                 province: current_user.province })
                                  .order(created_at: :desc)
                                  .limit(3)
    
        end
      
        def new
          @post = Post.new
        end
      
        def create
          @post = current_user.posts.build(post_params)
      
          if @post.save
            redirect_to resident_dashboard_path, notice: 'Post created successfully.'
          else
            render :new
          end
        end
      
        def edit
        end
      
        def update
          if @post.update(post_params)
            redirect_to resident_dashboard_path, notice: 'Post updated successfully.'
          else
            render :edit
          end
        end
      
        def destroy
          @post.destroy
          redirect_to resident_dashboard_path, notice: 'Post deleted successfully.'
        end
      
        private
      
        def set_post
          @post = current_user.posts.find(params[:id])
        end
      
        def post_params
          params.require(:post).permit(:title, :content)
        end
      end
      
end

app/controllers/resident/likes_controller.rb
class Resident::LikesController < ApplicationController
    class Resident::LikesController < ApplicationController
        def create
            @like = current_user.likes.new(like_params)
    
            if !@like.save
                flash[:notice] = @like.errors.full_messages.to_sentence
            end
    
            redirect_back(fallback_location: root_path)
        end
    
        def destroy
            @like = current_user.likes.find(params[:id])
            post = @like.post
            @like.destroy
            redirect_back(fallback_location: root_path)
        end
    
        private
    
        def like_params
            params.require(:like).permit(:post_id)
        end
    end
    
end

app/controllers/resident/posts_controller.rb
class Resident::PostsController < ApplicationController
    before_action :authenticate_user!

    def index
      current_user_location = {
        province: current_user.province,
        city_municipality: current_user.city_municipality,
        barangay: current_user.barangay
      }
  
      @posts = Post.joins(:user)
                       .where(users: { status: 'approved', province: current_user_location[:province], city_municipality: current_user_location[:city_municipality], barangay: current_user_location[:barangay] })
      @comments = Comment.all
  
      if params[:content_query].present?
        @posts = @posts.where("LOWER(content) LIKE ?", "%#{params[:content_query].downcase}%")
      end
    
    end
  
    def my_posts
      @user_posts = current_user.posts 
    end
  
    def new
      @post = Post.new
    end
  
    def create
      @post = current_user.posts.build(post_params)
  
      if @post.save
        redirect_to resident_posts_path notice: 'Post created successfully.'
      else
        render :new
      end
    end
  
    private
  
    def post_params
      params.require(:post).permit(:title, :content, :anonymous)
    end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/residents_helper.rb
module Admin::ResidentsHelper
end

app/helpers/resident/announcements_helper.rb
module Resident::AnnouncementsHelper
end

app/helpers/resident/comments_helper.rb
module Resident::CommentsHelper
end

app/helpers/resident/complaints_helper.rb
module Resident::ComplaintsHelper
end

app/helpers/resident/dashboard_helper.rb
module Resident::DashboardHelper
end

app/helpers/resident/likes_helper.rb
module Resident::LikesHelper
end

app/helpers/resident/posts_helper.rb
module Resident::PostsHelper
end

app/views/resident/dashboard/_form.html.erb
<%= form_with(model: @post, url: resident_dashboard_index_path, local: true) do |form| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div>
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>
  
    <div>
      <%= form.submit "Create Post" %>
    </div>
  <% end %>

app/views/resident/dashboard/index.html.erb
<% if current_user.approved? %>
  <div class="resident-dash-wrapper">
    <div class="user-profile-wrapper">
      <div class="profile-top-container">
        <div class="avatar-container" id="avatar-pic">
          <% if current_user.image.attached? %>
            <%= image_tag(current_user.image, style: "height:100px; width:100px", class: 'avatar') %>
          <% else %>
          <div class="avatar-initials" id="image-container"><%= current_user.first_name[0] + current_user.last_name[0] %></div>
          <% end %>
        </div>
        <div class="profile-name"><h2><%= current_user.first_name.upcase %> <%= current_user.last_name.upcase %><h2>
        </div>
        </div>
        <div class="profile-content">
          <p><strong style="color: #5C821A;">Email:</strong> <%= current_user.email %></p>
    <p><strong style="color: #5C821A;">Contact Number:</strong> <%= current_user.contact_number %></p>
    <p><strong style="color: #5C821A;">Complete Address:</strong> <%= current_user.complete_address.titleize %></p>
    <p><strong style="color: #5C821A;">Regitration Date:</strong> <%= current_user.created_at.in_time_zone('Asia/Manila').strftime('%d %b %Y, %H:%M:%S') %></p>
        </div>
      </div>
    </div>

    <div class="dash-container">
    <div class="dash-header">
      <h2>Latest announcements</h2>
      <%= link_to "View All Announcements", resident_announcements_path, class: "action-link" %>
    </div>

    <div class="residents-dash-index">
    
      <% if @announcements.any? %>
        <% @announcements.each do |announcement| %>
          <div class="indiv-resident">
            <h2><%= link_to announcement.title, resident_announcement_path(announcement), class: "name-link" %></h2>
            <p><small>Posted at: <%= announcement.created_at.in_time_zone('Asia/Manila').strftime('%d %b %Y, %H:%M:%S') %> || Updated at: <%= announcement.updated_at.in_time_zone('Asia/Manila').strftime('%d %b %Y, %H:%M:%S') %></small></p>
            <p><%= truncate(announcement.content, length: 200) %></p>
          </div>
        <% end %>
      <% else %>
        <p>No announcements found.</p>
      <% end %>
    </div>
   
  </div>
  </div>

  <div id="upload-pic-modal" class="pic-modal">
  <div class="comment-modal-content">
    <div class="comment-modal-top">
    <h2 class="modal-title">Upload Profile Picture</h2> 
    <span class="comment-close">&times;</span>
  </div>
  <div class="comment-modal-body">
    <%= form_with(model: current_user, url: update_profile_picture_path, local: true, html: { id: "profile-picture-form", method: :patch, multipart: true }) do |form| %>
      <div class="field">
        <%= form.file_field :image, id: "profile-picture-file-field"  %>
      </div>
      <div class="modal-actions">
        <%= form.submit "Upload", class: "search-submit", disabled: true %>
      </div>
    <% end %>
</div>

<% else %>
  <div class="pending-dash">
    <p>Hi, <strong><%= current_user.first_name %></strong>! Your registration status is currently <strong><%= current_user.status.upcase %></strong>. Please wait for an email confirmation to be sent to <strong><%= current_user.email %></strong>.</p><br>
    <p>Thank you for your patience!</p>
  </div>
<% end %>
<script>
    var modal1 = document.getElementById("upload-pic-modal");
    var span1 = document.getElementsByClassName("comment-close")[0];

    document.getElementById('avatar-pic').addEventListener('click', function() {
    modal1.style.display = "block";
  });

  span1.addEventListener('click', function() {
    modal1.style.display = "none";
  });

  document.getElementById("profile-picture-form").addEventListener("submit", function() {
    modal1.style.display = "none";
  });

  document.getElementById('profile-picture-file-field').addEventListener('change', function() {
    document.querySelector('.search-submit').disabled = !this.value;
  });

</script>