config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'psgc/fetch_provinces', to: 'psgc#fetch_provinces'
    get 'psgc/fetch_cities_municipalities/:province_code', to: 'psgc#fetch_cities_municipalities'
    get 'psgc/fetch_barangays/:city_or_municipality_code', to: 'psgc#fetch_barangays'
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    root to: "devise/sessions#new"
  end
  
  patch 'profile/update_profile_picture', to: 'profile#update_profile_picture', as: 'update_profile_picture'
  
  namespace :admin do
    resources :dashboard, only: [:index] do
      post :create_admin_account, on: :collection
    end
    
    resources :residents do
      collection do
        get 'pending', to: 'residents#pending'
      end
    end 
    
    resources :announcements
    resources :complaints, only: [:index, :edit, :update, :show]
    resources :posts
  end


  namespace :resident do
    resources :dashboard, only: [:index]
    resources :posts, only: [:index, :new, :create, :show] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
      collection do
        get 'my_posts', to: 'posts#my_posts'
      end
    end
    resources :announcements, only: [:index, :show]
    resources :complaints, only: [:index, :show, :new, :create]
    
  end
end


app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :user

  validates :title, :content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :user
  validates :subject, :description, presence: true
  enum status: { pending: 'pending', resolved: 'resolved'}
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }
  
  belongs_to :user, optional: true
  belongs_to :post, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  validates :title, :content, presence: true
  validates_inclusion_of :anonymous, in: [true, false]

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

  validates :first_name, :last_name, :email, :complete_address, :province, :city_municipality, :barangay, :role, :status, presence: true
  validates :contact_number, presence: true, numericality: { only_integer: true }, length: { is: 11 }

  enum role: { admin: 'admin', resident: 'resident' }
  enum status: { pending: 'pending', approved: 'approved', rejected: 'rejected' }

  has_many :announcements, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :complaints, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  after_create :send_status_email

  private

  def send_status_email
    UserMailer.registration_confirmation(self).deliver_later

    if status == 'pending'
      UserMailer.pending_email(self).deliver_later
    end
  end

end

app/controllers/admin/announcements_controller.rb
class Admin::AnnouncementsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_announcement, only: [:show, :edit, :update, :destroy]

    def index
        @announcements = Announcement.joins(:user)
        .where(users: { role: 'admin', 
                       barangay: current_user.barangay, 
                       city_municipality: current_user.city_municipality,
                       province: current_user.province })
        .order(created_at: :desc)
    end

    def show
    end

    def new
        @announcement = Announcement.new
    end

    def create
        @announcement = Announcement.new(announcement_params)
        @announcement.user = current_user

        if @announcement.save
            redirect_to admin_announcements_path, notice: 'Announcement was successfully published.'
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        if @announcement.update(announcement_params)
            redirect_to admin_announcements_path, notice: 'Announcement was successfully updated.'
        else
            render :edit
        end
    end

    def destroy
        @announcement.destroy
        redirect_to admin_announcements_path, notice: 'Announcement was successfully deleted.'
    end

    private

    def set_announcement
        @announcement = Announcement.find(params[:id])
    end

    def announcement_params
        params.require(:announcement).permit(:title, :content)
    end

end

app/controllers/api/psgc_controller.rb
class Api::PsgcController < ApplicationController
    def fetch_provinces
        provinces = PSGC::Client.fetch_provinces
        render json: provinces
      end
    
      def fetch_cities_municipalities
        province_code = params[:province_code]
        cities_municipalities = PSGC::Client.fetch_cities_municipalities(province_code)
        render json: cities_municipalities
      end
    
      def fetch_barangays
        city_or_municipality_code = params[:city_or_municipality_code]
        barangays = PSGC::Client.fetch_barangays(city_or_municipality_code)
        render json: barangays
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
        if resource.admin?
            admin_dashboard_index_path
        else
            resident_dashboard_index_path
         end
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [
          :first_name, :last_name, :role,
          :complete_address, :province, :city_municipality, :barangay, :status, :contact_number
        ])
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
    before_action :authenticate_user!

  def update_profile_picture
    if current_user.update(user_params)
      redirect_to resident_dashboard_index_path, notice: 'Profile picture updated successfully.'
    else
      redirect_to resident_dashboard_index_path, alert: 'Profile picture not uploaded.'
    end
  end

  private

  def user_params
    params.require(:user).permit(:image)
  end
end

app/controllers/resident/announcements_controller.rb
class Resident::AnnouncementsController < ApplicationController
    def index
        @announcements = Announcement.joins(:user)
                                .where(users: { role: 'admin', 
                                               barangay: current_user.barangay, 
                                               city_municipality: current_user.city_municipality,
                                               province: current_user.province })
                                .order(created_at: :desc)
      end
    
      def show
        @announcement = Announcement.find(params[:id])
      end
end

app/helpers/admin/announcements_helper.rb
module Admin::AnnouncementsHelper
end

app/helpers/admin/complaints_helper.rb
module Admin::ComplaintsHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/residents_helper.rb
module Admin::ResidentsHelper
end

app/helpers/api/psgc_helper.rb
module Api::PsgcHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/resident/announcements_helper.rb
module Resident::AnnouncementsHelper
end

app/helpers/resident/comments_helper.rb
module Resident::CommentsHelper
end

app/helpers/resident/dashboard_helper.rb
module Resident::DashboardHelper
end

app/helpers/resident/likes_helper.rb
module Resident::LikesHelper
end

app/helpers/resident/posts_helper.rb
module Resident::PostsHelper
end

app/views/admin/announcements/_form.html.erb
<%= form_with(model: [:admin, @announcement], url: @announcement.persisted? ? admin_announcement_path(@announcement) : admin_announcements_path, local: true, class: "announcement-form") do |form| %>

  <% if @announcement.errors.any? %>
    <div style="color: red;">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
        <% @announcement.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="announcement-field">
  <%= form.label :title %>
  <%= form.text_field :title, required: true, class: "announcement-input" %>
</div>

<div class="announcement-field">
  <%= form.label :content %>
  <%= form.text_area :content, required: true, class: "announcement-input announcement-text-area" %>
</div>


  <div class="actions">
    <%= form.submit "Submit", class: "user-submit action-link" %>
  </div>
<% end %>

app/views/admin/announcements/edit.html.erb
<h1 class="page-title">Edit Announcement</h1>
<%= render 'form' %>

app/views/admin/announcements/index.html.erb
<div class="residents-index-wrapper">
<h1 class="page-title">Announcements For BRGY.<%= current_user.barangay.upcase %></h1>

  <div class="residents-index-actions">
<%= link_to "New Announcement", new_admin_announcement_path, class: "action-link" %>
</div>

<div class="residents-index-container">
<% @announcements.order(created_at: :desc).each do |announcement| %>
  <div class="indiv-resident">
    <h3><%= link_to announcement.title, admin_announcement_path(announcement), class: "name-link" %></h3>
    <p>Created at: <%= announcement.created_at.strftime("%d %b %Y %H:%M:%S") %></p>
    <p>Updated at: <%= announcement.updated_at.strftime("%d %b %Y %H:%M:%S") %></p>
    <p><%= truncate(announcement.content, length: 200) %></p>
  </div>
<% end %>
</div>
</div>

app/views/admin/announcements/new.html.erb
<h1 class="page-title">Create New Announcement</h1>
<%= render 'form' %>

app/views/admin/announcements/show.html.erb
<div class="show-announcement-wrapper">
  <h1 class="page-title"><%= @announcement.title %></h1>

  <div class="show-announcement-details">
    <p><strong style="color: #5C821A;">Posted by:</strong> <%= current_user.first_name.titleize %></p>
    <p><strong style="color: #5C821A;">Created At:</strong> <%= @announcement.created_at.strftime("%d %b %Y %H:%M:%S") %></p>
    <p><strong style="color: #5C821A;">Updated At:</strong> <%= @announcement.updated_at.strftime("%d %b %Y %H:%M:%S") %></p>
    <p><strong style="color: #5C821A;">Content:</strong> <%= @announcement.content %></p>

    <div class="show-announcement-actions">
      <%= link_to 'Back', admin_announcements_path, class: "action-link" %>
      <%= link_to 'Edit', edit_admin_announcement_path(@announcement), class: "action-link" %>
      <%= button_to 'Destroy', admin_announcement_path(@announcement), method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-button action-link"  %>
    </div>
  </div>
</div>