config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'psgc/fetch_provinces', to: 'psgc#fetch_provinces'
    get 'psgc/fetch_cities_municipalities/:province_code', to: 'psgc#fetch_cities_municipalities'
    get 'psgc/fetch_barangays/:city_or_municipality_code', to: 'psgc#fetch_barangays'
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    root to: "devise/sessions#new"
  end
  
  patch 'profile/update_profile_picture', to: 'profile#update_profile_picture', as: 'update_profile_picture'
  
  namespace :admin do
    resources :dashboard, only: [:index] do
      post :create_admin_account, on: :collection
    end
    
    resources :residents do
      collection do
        get 'pending', to: 'residents#pending'
      end
    end 
    
    resources :announcements
    resources :complaints, only: [:index, :edit, :update, :show]
    resources :posts
  end


  namespace :resident do
    resources :dashboard, only: [:index]
    resources :posts, only: [:index, :new, :create, :show] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
      collection do
        get 'my_posts', to: 'posts#my_posts'
      end
    end
    resources :announcements, only: [:index, :show]
    resources :complaints, only: [:index, :show, :new, :create]
    
  end
end


app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :user

  validates :title, :content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :user
  validates :subject, :description, presence: true
  enum status: { pending: 'pending', resolved: 'resolved'}
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }
  
  belongs_to :user, optional: true
  belongs_to :post, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  validates :title, :content, presence: true
  validates_inclusion_of :anonymous, in: [true, false]

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

  validates :first_name, :last_name, :email, :complete_address, :province, :city_municipality, :barangay, :role, :status, presence: true
  validates :contact_number, presence: true, numericality: { only_integer: true }, length: { is: 11 }

  enum role: { admin: 'admin', resident: 'resident' }
  enum status: { pending: 'pending', approved: 'approved', rejected: 'rejected' }

  has_many :announcements, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :complaints, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  after_create :send_status_email

  private

  def send_status_email
    UserMailer.registration_confirmation(self).deliver_later

    if status == 'pending'
      UserMailer.pending_email(self).deliver_later
    end
  end

end

app/controllers/api/psgc_controller.rb
class Api::PsgcController < ApplicationController
    def fetch_provinces
        provinces = PSGC::Client.fetch_provinces
        render json: provinces
      end
    
      def fetch_cities_municipalities
        province_code = params[:province_code]
        cities_municipalities = PSGC::Client.fetch_cities_municipalities(province_code)
        render json: cities_municipalities
      end
    
      def fetch_barangays
        city_or_municipality_code = params[:city_or_municipality_code]
        barangays = PSGC::Client.fetch_barangays(city_or_municipality_code)
        render json: barangays
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
        if resource.admin?
            admin_dashboard_index_path
        else
            resident_dashboard_index_path
         end
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [
          :first_name, :last_name, :role,
          :complete_address, :province, :city_municipality, :barangay, :status, :contact_number
        ])
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
    before_action :authenticate_user!

  def update_profile_picture
    if current_user.update(user_params)
      redirect_to resident_dashboard_index_path, notice: 'Profile picture updated successfully.'
    else
      redirect_to resident_dashboard_index_path, alert: 'Profile picture not uploaded.'
    end
  end

  private

  def user_params
    params.require(:user).permit(:image)
  end
end

app/helpers/admin/complaints_helper.rb
module Admin::ComplaintsHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/residents_helper.rb
module Admin::ResidentsHelper
end

app/helpers/api/psgc_helper.rb
module Api::PsgcHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/resident/comments_helper.rb
module Resident::CommentsHelper
end

app/helpers/resident/likes_helper.rb
module Resident::LikesHelper
end

app/helpers/resident/posts_helper.rb
module Resident::PostsHelper
end

app/views/layouts/_navbar.html.erb
<nav>
    <div class='web-title-container'>
            <h2 id='web-title'>Barangay Portal</h2>
    </div>

    <div>
        <ul class='nav-links-container'>
            <% if user_signed_in? %>
                <% if current_user.pending? %>
                    <li class='nav-links'><%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete, confirm: "Are you sure you want to sign out?" } %></li>
                <% elsif current_user.admin? %>
                    <li class='nav-links'><%= link_to "Home", admin_dashboard_index_path %></li>
                    <li class='nav-links'><%= link_to "Residents", admin_residents_path %></li>
                    <li class='nav-links'><%= link_to "Complaints", admin_complaints_path %></li>
                    <li class='nav-links'><%= link_to "Announcements", admin_announcements_path %></li>
                    <li class='nav-links'><%= link_to "Posts", admin_posts_path %></li>
                    <li class='nav-links'><%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete, confirm: "Are you sure you want to sign out?" } %></li>
                <% else %>
                    <li class='nav-links'><%= link_to "Home", resident_dashboard_index_path %></li>
                    <li class='nav-links'><%= link_to "Posts", resident_posts_path %></li>
                    <li class='nav-links'><%= link_to "Complaints", resident_complaints_path %></li>
                    <li class='nav-links'><%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete, confirm: "Are you sure you want to sign out?"  } %></li>
                <% end %>
                
            <% else %>
                <li class='nav-links'><%= link_to 'Sign In', new_user_session_path %></li>
                <li class='nav-links'><%= link_to 'Sign Up', new_user_registration_path %></li>
            <% end %>
            <button class="hamburger">
            <div class="bar"></div>
            </button>
        </ul>
    </div>
</nav>

<div>
<ul class='mobile-nav'>
        <% if user_signed_in? %>
            <% if current_user.pending? %>
                <li class='mobile-nav-links'><%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete, confirm: "Are you sure you want to sign out?" } %></li>
            <% elsif current_user.admin? %>
                <li class='mobile-nav-links'><%= link_to "Home", admin_dashboard_index_path %></li>
                <li class='mobile-nav-links'><%= link_to "Residents", admin_residents_path %></li>
                <li class='mobile-nav-links'><%= link_to "Complaints", admin_complaints_path %></li>
                <li class='mobile-nav-links'><%= link_to "Announcements", admin_announcements_path %></li>
                <li class='mobile-nav-links'><%= link_to "Posts", admin_posts_path %></li>
                <li class='mobile-nav-links'><%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete, confirm: "Are you sure you want to sign out?" } %></li>
            <% else %>
                <li class='mobile-nav-links'><%= link_to "Home", resident_dashboard_index_path %></li>
                <li class='mobile-nav-links'><%= link_to "Posts", resident_posts_path %></li>
                <li class='mobile-nav-links'><%= link_to "Complaints", resident_complaints_path %></li>
                <li class='mobile-nav-links'><%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete, confirm: "Are you sure you want to sign out?"  } %></li>
            <% end %>
            
        <% else %>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
        </ul>
    </div>

<script>
    var menu_btn = document.querySelector(".hamburger");
    var phone_menu = document.querySelector(".mobile-nav");
    
    menu_btn.addEventListener("click", () => {
        menu_btn.classList.toggle("is-active");
        phone_menu.classList.toggle("is-active");
    })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarangayCommunicationPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class='flash-container'>
     <% flash.each do |key, value| %>
      <div class="<%= key %>">
        <%= value %>
      </div>
    <% end %>
    </div>
    <div>
    <%= yield %>
    </div>
  </body>
</html>